#!/usr/bin/env bash

set -euo pipefail

exec 2>&1

export PYTHONPATH=.

if [[ -e ~/.spackle_pidfile ]]; then
    spackle_pid=$(cat ~/.spackle_pidfile)
    echo "Stopping running spackle with pid $spackle_pid"
    kill "$spackle_pid"
    echo -n "Waiting for spackle to stop..."
    while [[ -d "/proc/$spackle_pid" ]]; do
        sleep 0.25
        echo -n "."
        if [[ $SECONDS -gt 10 ]]; then
            echo ""
            echo "Spackle refused to stop. I give up."
            exit 1
        fi
    done
    echo "...stopped!"
fi

.venv/bin/python3 -m spackle &> ~/spackle.log &

echo $! > ~/.spackle_pidfile

echo "Started Spackle with pid $(cat ~/.spackle_pidfile)"
